# The default build for wasp-os. Modify to customize your own build.
# At least one watch face must be specified. Quick ring apps will be added in order.

[[app]]
file = 'apps/flashlight.py'
quick_ring = true

[[app]]
file = 'apps/stopwatch.py'
quick_ring = true

[[app]]
file = 'apps/heart.py'
quick_ring = true

[[app]]
file = 'apps/alarm.py'
auto_load = true

[[app]]
file = 'apps/timer.py'
auto_load = true

[[watchface]]
file = 'watch_faces/clock.py'

[[watchface]] # Requires ClockApp to also be installed
file = 'watch_faces/week_clock.py'
default = true