# The default build for wasp-os. Modify to customize your own build.
# At least one watch face must be specified. Quick ring apps will be added in order.

[[app]]
file = 'apps/stopwatch.py'
quick_ring = true

[[app]]
file = 'apps/heart.py'
quick_ring = true

[[app]]
file = 'apps/alarm.py'
auto_load = true

[[app]]
file = 'apps/timer.py'
auto_load = true

[[app]]
file = 'apps/calculator.py'

[[app]]
file = 'apps/disa_b_l_e.py'

[[app]]
file = 'apps/wine.py'
auto_load = true

[[app]]
file = 'apps/flashlight.py'
auto_load = true

 
[[watchface]]
file = 'watch_faces/terminal.py'
default = true